// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	UserID    pgtype.UUID      `db:"user_id" json:"user_id"`
	Email     string           `db:"email" json:"email"`
	Password  string           `db:"password" json:"password"`
	Name      pgtype.Text      `db:"name" json:"name"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	IsActive  pgtype.Bool      `db:"is_active" json:"is_active"`
}
