// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ============================================
	// ADMIN ONLY
	// ============================================
	AdminHardDeleteUser(ctx context.Context, userID pgtype.UUID) error
	// ============================================
	// BATCH OPERATIONS
	// ============================================
	BulkDeactivateUsers(ctx context.Context, dollar_1 []pgtype.UUID) error
	CheckUserExists(ctx context.Context, email string) (bool, error)
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	// ============================================
	// USER CREATION
	// ============================================
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// ============================================
	// USER STATUS MANAGEMENT
	// ============================================
	DeactivateUser(ctx context.Context, userID pgtype.UUID) error
	// ============================================
	// DATA INTEGRITY
	// ============================================
	GetDuplicateEmails(ctx context.Context) ([]GetDuplicateEmailsRow, error)
	// ============================================
	// USER AUTHENTICATION QUERIES
	// ============================================
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, userID pgtype.UUID) (User, error)
	GetUserForValidation(ctx context.Context, userID pgtype.UUID) (GetUserForValidationRow, error)
	// ============================================
	// ANALYTICS
	// ============================================
	GetUserStats(ctx context.Context) (GetUserStatsRow, error)
	GetUsersByDateRange(ctx context.Context, arg GetUsersByDateRangeParams) ([]GetUsersByDateRangeRow, error)
	ListActiveUsers(ctx context.Context, arg ListActiveUsersParams) ([]ListActiveUsersRow, error)
	// ============================================
	// LISTING & PAGINATION
	// ============================================
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	ReactivateUser(ctx context.Context, userID pgtype.UUID) error
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (UpdateUserEmailRow, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// ============================================
	// USER PROFILE UPDATES
	// ============================================
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error)
}

var _ Querier = (*Queries)(nil)
